version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - echo "nothing to do in install"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - echo "dump environment"
      - env
      - echo "Finished build `date` in `pwd`"
  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://${SOLUTIONS_BUILD_ASSETS_BUCKET}/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"

artifacts:
  files:
    - "**/*"
